let suggestions = [
    "Anorexia Nervosa",
    "Bulimia Nervosa",
    "Exercise Bulimia",
    "Binge Eating Disorder (BED)",
    "Pica",
    "Rumination Disorder",
    "Suicidal Ideation",
    "Anxiety",
    "Depression",
    "Bipolar Disorder",
    "Bipolar (Depression)",
    "Bipolar (Mania)",
    "Schizophrenia",
    "Body Dysmorphic Disorder (BDD)",
    "Attention Deficit Hyperactivity Disorder (ADHD)",
    "Attention Deficit Disorder (ADD)",
    "Posttraumatic Stress Disorder (PTSD)",
    "Obsessive-Compulsive Disorder (OCD)",
    "Autism Spectrum Disorder (ASD)",
    "Antisocial Personality Disorder (APD)",
    "Borderline Personality Disorder (BPD)",
    "Narcissistic Personality Disorder (NPD)",
    "Avoidant Personality Disorder (APD)",
    "Generalized Anxiety Disorder (GAD)",
    "Intermittent Explosive Disorder (IED)",
    "Anorexia Athletica",
];
